---
title: Unsere Praxis
---

Unsere Praxis befindet sich direkt gegenüber vom beliebten Findorffmarkt und dem Torfhafen im Herzen von Findorff.

Unsere Sprechstunden unterscheiden wir nach Art wie folgend:

Die Terminsprechstunde ist gedacht, um die Wartezeiten kurz zu halten und auf alle Ihre Anliegen mit der gebührenden Zeit eingehen zu können. Diese ist u.a. für planbare Untersuchungen/Behandlungen. Beispiele: länger bestehende Symptome oder Erkrankungen, Gesundheitsvorsorge, Impfungen, Bescheinigungen u.ä.
Für an der hausarztzentrierten Versorgung (HzV) Teilnehmende können erweiterte Sprechstundenzeiten angeboten werden.

Die Akut- und Infektsprechstunde findet als offene Sprechstunde statt (ohne Termin, mit Wartezeit). Diese ist für Anliegen, bei denen ein dringender Kontakt notwendig ist. Auch akute, vermutlich infektiöse Erkrankungen zählen hierzu. Beispiele: akute Rückenschmerzen, grippaler Infekt, Gastroenteritis. Bitte beachten Sie, dass – trotz des ganzheitlichen Ansatzes unserer Behandler:innen – in der Akutsprechstunde nur das akute Anliegen besprochen werden kann. Für weitere Fragen buchen Sie bitte einen Termin in unserer Terminsprechstunde.

Dringende Arbeitsunfähigkeitsbescheinigungen (AU)

Termine können Sie online buchen, oder telefonisch abstimmen.